name: ROS CD

on:
  pull_request:
    branches: [ main ] # run only when making a PR for main

jobs:
  build-and-push:
    name: Build & Push main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # you fill in the rest
      # tutorial: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
      #
      # - name: Build foxy amd64
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: eu.gcr.io/ascend/ros-amd64:main
      #     platforms: linux/amd64
      # - name: Build foxy arm64
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: eu.gcr.io/ascend/ros-arm64:main
      #     platforms: linux/arm64
